### ISSUE TITLE
Folder structure configuration

### ISSUE THREAD

**Issue by oscarloch** [dongkyuk/CheXFusion#3]
Hello, I attempted to use the code but encountered difficulty in determining the appropriate folder structure for training the model.

1. What file (or path) do I need to modify to commence training?
2. What is the appropriate folder structure for training the model? Could you specify the one you utilized?

I already have the mimic-cxr-jpg and chexpert downloaded but currently I can't configure this model correctly.

I'm sorry if my question is too elementary. Thank you so much for your help.

**Comment by dongkyunk** [comment]
Hi, please refer to chexpert_dataset and cxr_dataset.
This code is designed for use of multiple datasets, so you will also have to also edit the datamodule code.
About the folder structure, you can refer to the code.
